server:
  port: 8080
  servlet:
    context-path: /base

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/baselts"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 444444
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"